name: Sonarqube

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['UV']
    types: [completed]

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Download coverage report
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          name: code-coverage-report
          github-token: ${{ secrets.ARTEFACT_TOKEN }}
      - uses: sonarsource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
